version: "3.8"

services:
  app:
    container_name: property-marketplace-backend
    image: odiasesamuel/property-marketplace-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: npm start
